// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbb222bbbbbbbbbb222bbb...
.....bbb222bbbbbbbbbb222bbb...
.....bbb222bbbbbbbbbb222bbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbb1111111111111bbbb...
.....bbbbb1111111111111bbbb...
.....bbbbb1111111111111bbbb...
.....bbbbb1111111111111bbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
.....bbbbbbbbbbbbbbbbbbbbbb...
`;
            case "image2":
            case "myImage0":return img`
....................444444444444..................
............33ae4444444444444444444eaaaa..........
..........333aae444444444444444444eaaaaaa.........
......5...3aaaaae44444444444444444eaaaaaaa.555....
....5..5.33aaaaae44444444444444444eaaaaaaa55..55..
.....5..53aaaaaaae4444444444444444eaaaaaaa5555....
.5...55553aaaaaaaa4444444444444444eaaaaaaa555.....
..55555553aaaaaaaae44444444444444eaaaacaaaa55555..
....555553aaaaaaaaaeeeeeeeeeeeeeeeaaaacaaaa555....
...55555aaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaaa555....
.55.5555aaaaaaccaaaaaaaaaaaaaaaaaaaaaccaaaa5555.5.
....5555aaaaaacaaaaaaaaaaaaaaaaaaaaaccaaaaa555.55.
...55555aaaaaacaaaaaaaaaaaaaaaaaaaaccaaaaaa555....
..5.5555aaaaaccaaaaaaaccaaaaaaaaaaccaaaaaa555555..
....5555aaaaacaaaaaaaccccaaaaaaaaaaaaaaaaa5555.5..
...5..55aaaaacaaaaaaacccaaaaaaaaaaaaaaaaaa5555....
.....5.5aaaaacaaaaaaaccaaaaaaaaaaaaaaaaaa5555555..
.......aaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaac...5..5..
........aaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaac..55....
.........caaaaaaaaaaaccaaaaaaaaaaaaaaaaaac........
.........caaaaaaaaaaaccaaaaaaaaaaaaaaaacac........
.........ccaaaaaaaaacccaaaaccaaaaaaaaaccac........
.........ccaaaaaaaaacccaaaaaccaaaaaaaaccac........
.........ccaaaaaaaaacccaaaaaccaaaaaaaaccaa........
.........cccaaaaaaaaccaaaaaaaccaaaaaacccaa........
.........cccaaaaaaaaccaaaaaaaccaaaaaacccca........
.........cccaaaaaaaaaaaaaaaaacaaaaaaccccca........
.........ccccaaaaaaaaaaaaaaaacaaaaacccccca........
.........acccaaacccaaaaaaaaaacaaaaacccccca........
.........acccaaaaccaaaaaaaaaccaaaaacccccca........
.........acccaaaaaccaaaaaaaaccaaaaccccccaa........
.........cccccaaaaacccaaaaaaacaaaaccccccc.........
.........accccaaaaaaacccaaaaaaaaaaccccccc.........
.........accccaaaaaaaaacccaaaaaaacccccccc.........
........aacccccaaaaaaaaaccccaaaaaccccccca.........
........aaaccccaaaaaaaaaacccaaaaaccccccca.........
........aaaacccaaaaaaaaaaaccaaaacccccccca.........
.........aaaacccaaaaaaaaaaaaaaaaccaaaaaaa.........
.........aaaaaaaaaaaaaaaaaaaaaaaaaaaaaac..........
..........aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
